// Generated by toolkit/scripts/mirror-lifecycle-phases.mjs. Do not edit.
export const PHASES = Object.freeze(["discovery","plan","critic","tdd","verify","review","refutation","harden","report"]);
export const LOOP_BOUNDS = Object.freeze({"plan":3,"critic":3,"review":3,"refutation":3,"harden":2});
