// Generated by toolkit/scripts/mirror-lifecycle-phases.mjs. Do not edit.
export const PHASES = Object.freeze(["discovery","plan","critic","tdd","verify","review","refutation","report"]);
export const LOOP_BOUNDS = Object.freeze({"plan":6,"critic":6});
