// Generated by toolkit/scripts/mirror-lifecycle-phases.mjs. Do not edit.
export const PHASES = Object.freeze(["discovery","plan","critic","tdd","verify","review","refutation","harden","report"]);
export const LOOP_BOUNDS = Object.freeze({"plan":6,"critic":6,"review":6,"refutation":6,"harden":5});
