// Generated by dwt:scaffold — a STARTING POINT, not a finished workflow.
// Replace the placeholder items/claims/tasks and prompt text with your own, and add
// "as const satisfies JsonSchema" schemas at each consumed agent boundary (see the
// workflow-composer skill). Then build and check:
//   pnpm dwt:build <this-file>   &&   pnpm dwt:check workflows/<name>.js

import { defineWorkflow } from '@workflow-toolbox/build/define'
import { classifyAndAct, fanOutAndSynthesize, adversarialVerification, generateAndFilter, tournament, loopUntilDone, planAndExecute } from '@workflow-toolbox/patterns'

export default defineWorkflow({
  meta: {
    name: "all-patterns-demo",
    description: "A scaffold exercising every pattern (typecheck + lint fixture).",
    phases: [{ title: "Route" }, { title: "Analyze" }, { title: "Verify" }, { title: "Generate" }, { title: "Compete" }, { title: "Refine" }, { title: "Execute" }],
  },
  run: async (rt) => {
    const step1 = await classifyAndAct(rt, {
      items: ['placeholder-item'],
      categories: ['category-a', 'category-b'],
      classifyPrompt: (item) => `Classify this item into category-a or category-b: ${item}`,
      actions: {
        'category-a': { prompt: (item) => `Handle the category-a item: ${item}` },
        'category-b': { prompt: (item) => `Handle the category-b item: ${item}` },
      },
      phase: "Route",
    })

    const step2 = await fanOutAndSynthesize(rt, {
      tasks: ['placeholder-task'],
      taskPrompt: (task, index) => `Work item ${index}: ${task}`,
      synthesisPrompt: (parts) => `Synthesize the ${parts.length} partial results.`,
      phase: "Analyze",
    })

    const step3 = await adversarialVerification(rt, {
      claims: ['placeholder-claim'],
      renderClaim: (claim) => `Verify this claim, refuting if uncertain: ${claim}`,
      phase: "Verify",
    })

    const step4 = await generateAndFilter(rt, {
      count: 3,
      generatePrompt: (index) => `Generate candidate number ${index}.`,
      filterPrompt: (candidate) => `Keep this candidate? ${candidate}`,
      phase: "Generate",
    })

    const step5 = await tournament(rt, {
      angles: ['angle-a', 'angle-b'],
      attemptPrompt: (angle, index) => `Attempt ${index} from this angle: ${angle}`,
      judgePrompt: (attempt) => `Score this attempt: ${attempt}`,
      synthesisPrompt: (ranked) => `Synthesize the best of ${ranked.length} ranked attempts.`,
      phase: "Compete",
    })

    rt.phase("Refine")
    const step6 = await loopUntilDone(rt, {
      initial: { rounds: 0 },
      maxIterations: 3,
      body: async (rt, state, iteration) => {
        await rt.agent(`Refinement iteration ${iteration}: improve the current draft.`)
        // TODO: replace the done condition below with your real stop check (e.g. an evaluator verdict).
        return { state: { rounds: state.rounds + 1 }, done: false }
      },
    })

    const step7 = await planAndExecute(rt, {
      planPrompt: 'Break the goal into independent subtasks.',
      workerPrompt: (subtask, index) => `Subtask ${index}: ${subtask.description}`,
      synthesisPrompt: (results) => `Combine the ${results.length} worker results.`,
      phase: "Execute",
    })

    return { step1: step1.value, step2: step2.value, step3: step3.value, step4: step4.value, step5: step5.value, step6: step6.value, step7: step7.value }
  },
})
