// Generated by workflow-toolbox scaffold — a STARTING POINT, not a finished workflow.
// Replace the placeholder items/claims/tasks and prompt text with your own, and add
// "as const satisfies JsonSchema" schemas at each consumed agent boundary (see the
// workflow-composer skill). Then build and check:
//   npx workflow-toolbox build <this-file>   &&   npx workflow-toolbox check workflows/<name>.js

import { defineWorkflow } from '@workflow-toolbox/build/define'
import { classifyAndAct, fanOutAndSynthesize, adversarialVerification, generateAndFilter, tournament, loopUntilDone, planAndExecute, scoreAndRank, chunkedAnalysis, withLeafFence } from '@workflow-toolbox/patterns'

export default defineWorkflow({
  meta: {
    name: "all-patterns-demo",
    description: "A scaffold exercising every pattern (typecheck + lint fixture).",
    phases: [{ title: "Fence" }, { title: "Route" }, { title: "Analyze" }, { title: "Verify" }, { title: "Generate" }, { title: "Compete" }, { title: "Refine" }, { title: "Execute" }, { title: "Triage" }, { title: "Chunk" }],
  },
  run: async (rt0) => {
    // Default leaf-agent fence: every agent this workflow spawns denies SendMessage
    // by default (see @workflow-toolbox/patterns' withLeafFence). Pass
    // `{ disabled: true }` only if this workflow genuinely needs its agents to coordinate.
    // Stages whose prompts are 100% inline (classify/score/dedup/synthesize, no
    // 'read the repo/diff' instruction) can also shed the ambient tool/skill injection:
    // route those call sites through withLeanRouting (selective, never blanket).
    const { rt } = await withLeafFence(rt0, { phase: 'Fence' })

    const step1 = await classifyAndAct(rt, {
      items: ['placeholder-item'],
      categories: ['category-a', 'category-b'],
      classifyPrompt: (item) => `Classify this item into category-a or category-b: ${item}`,
      actions: {
        'category-a': { prompt: (item) => `Handle the category-a item: ${item}` },
        'category-b': { prompt: (item) => `Handle the category-b item: ${item}` },
      },
      phase: "Route",
    })

    const step2 = await fanOutAndSynthesize(rt, {
      tasks: ['placeholder-task'],
      taskPrompt: (task, index) => `Work item ${index}: ${task}`,
      synthesisPrompt: (parts) => `Synthesize the ${parts.length} partial results.`,
      phase: "Analyze",
    })

    const step3 = await adversarialVerification(rt, {
      claims: ['placeholder-claim'],
      renderClaim: (claim) => `Verify this claim, refuting if uncertain: ${claim}`,
      phase: "Verify",
    })

    const step4 = await generateAndFilter(rt, {
      count: 3,
      generatePrompt: (index) => `Generate candidate number ${index}.`,
      filterPrompt: (candidate) => `Keep this candidate? ${candidate}`,
      phase: "Generate",
    })

    const step5 = await tournament(rt, {
      angles: ['angle-a', 'angle-b'],
      attemptPrompt: (angle, index) => `Attempt ${index} from this angle: ${angle}`,
      judgePrompt: (attempt) => `Score this attempt: ${attempt}`,
      synthesisPrompt: (ranked) => `Synthesize the best of ${ranked.length} ranked attempts.`,
      phase: "Compete",
    })

    rt.phase("Refine")
    const step6 = await loopUntilDone(rt, {
      initial: { rounds: 0 },
      maxIterations: 3,
      body: async (rt, state, iteration) => {
        await rt.agent(`Refinement iteration ${iteration}: improve the current draft.`)
        // TODO: replace the done condition below with your real stop check (e.g. an evaluator verdict).
        return { state: { rounds: state.rounds + 1 }, done: false }
      },
    })

    const step7 = await planAndExecute(rt, {
      planPrompt: 'Break the goal into independent subtasks.',
      workerPrompt: (subtask, index) => `Subtask ${index}: ${subtask.description}`,
      synthesisPrompt: (results) => `Combine the ${results.length} worker results.`,
      phase: "Execute",
    })

    const step8 = await scoreAndRank(rt, {
      items: ['placeholder-item'],
      dimensions: [
        { name: 'impact', prompt: (item) => `Score the impact of ${item} from 1 to 5.` },
        { name: 'opportunity', prompt: (item) => `Score the opportunity in ${item} from 1 to 5.` },
      ],
      cutoff: { type: 'topK', k: 3 },
      phase: "Triage",
    })

    // chunkedAnalysis fans out one agent per chunk of the input — size maxChars for
    // the analyze model. Tune cost/quality per role with analyzeModel/analyzeEffort/
    // analyzeType (+ the synthesize equivalents), or blanket-tune every agent in this
    // run via the launch-time `perAgent` knob (args.perAgent -> parseConfig ->
    // withAgentDefaults; see toolkit/examples/pr-review.workflow.ts for the idiom).
    const step9 = await chunkedAnalysis(rt, {
      input: 'placeholder-content-to-chunk',
      maxChars: 4000,
      analyzePrompt: (chunk, index, total) => `Analyze chunk ${index + 1} of ${total}: ${chunk}`,
      synthesizePrompt: (chunkResults) => `Synthesize these ${chunkResults.length} chunk analyses.`,
      phase: "Chunk",
    })

    return { step1: step1.value, step2: step2.value, step3: step3.value, step4: step4.value, step5: step5.value, step6: step6.value, step7: step7.value, step8: step8.value, step9: step9.value }
  },
})
