import { defineWorkflow } from '@workflow-toolbox/build/define'

/**
 * One phase. One agent. Ten external calls that the agent never composes.
 *
 * This exists to make ONE thing visible in the observatory: a thin-envelope phase whose
 * INPUT and OUTPUT both go through files, so the agent contributes nothing but flags.
 *
 * ⚠ Why it is shaped this way rather than as a pattern: the patterns can only route a role
 * to an agentType — none of them can invoke a script (verified: nothing under
 * packages/patterns/src imports child_process). The working configuration on 2026-08-16
 * was an agent handed `--each-json`-style FLAGS, so the script read the source file,
 * generated the tasks and wrote the answers. That is what this reproduces.
 *
 * ⚠ The agent MUST NOT be given the questions. The moment they are in its prompt it
 * composes the call, and a composing agent is the failure mode this run exists to avoid:
 * on 2026-08-27 one made three Bash calls of its own and never reached the CLI.
 *
 * The prompt keys below are the envelope agent's own documented contract — when
 * OPENCODE_EACH_LINES is present it writes nothing and makes exactly one Bash call.
 */
export default defineWorkflow({
  meta: {
    name: 'envelope-scripted-io',
    description:
      'One phase, one thin-envelope agent, ten external calls generated BY THE SCRIPT from a file — scripted input, scripted output, the agent only relays. Concurrency is caller-set so the call pattern is observable.',
    whenToUse:
      'To watch a thin-envelope phase in the observatory with nothing composed by an agent. Not a real analysis: the questions are trivial by design.',
    phases: [{ title: 'Ask', detail: 'one envelope agent, N script-generated calls' }],
  },
  // ⚠ `defineWorkflow` accepts { meta, parseInput?, run } — there is NO `input:` key. An earlier
  // version of this file used one; the args were then never validated and the first run succeeded
  // only because the values happened to match. A correct result from a mechanism that checks
  // nothing looks exactly like a correct result.
  parseInput: (raw: unknown) => {
    const o = (raw ?? {}) as Record<string, unknown>
    const str = (k: string) => {
      const v = o[k]
      if (typeof v !== 'string' || v.length === 0) {
        throw new Error(`envelope-scripted-io: "${k}" must be a non-empty string`)
      }
      return v
    }
    const concurrency = o.concurrency === undefined ? 8 : o.concurrency
    if (typeof concurrency !== 'number' || !Number.isInteger(concurrency) || concurrency < 1) {
      throw new Error('envelope-scripted-io: "concurrency" must be an integer >= 1')
    }
    return {
      sourceFile: str('sourceFile'),
      workdir: str('workdir'),
      concurrency,
      model: typeof o.model === 'string' && o.model ? o.model : 'openai/gpt-5.4',
    }
  },
  run: async (rt, input: { sourceFile: string; workdir: string; concurrency: number; model: string }) => {
    rt.phase('Ask')

    // Everything the agent needs is a FLAG. The questions are never in this prompt —
    // that is the whole point, and the reason the source file is passed by path.
    const answer = await rt.agent(
      [
        'OPENCODE_EACH_LINES: ' + input.sourceFile,
        'OPENCODE_PROMPT_TEMPLATE: Answer in big-O notation only, nothing else: {{item}}',
        'OPENCODE_ID_TEMPLATE: {{item}}',
        'OPENCODE_CONCURRENCY: ' + String(input.concurrency),
        'OPENCODE_MODEL: ' + input.model,
        'OPENCODE_WORKDIR: ' + input.workdir,
        '',
        'Make the one Bash call your instructions describe for this shape, then relay its',
        'printed output verbatim. Do not read the source file. Do not read any answer file.',
      ].join('\n'),
      {
        label: 'envelope:scripted-io',
        agentType: 'workflow-toolbox:opencode-envelope',
      },
    )

    // The manifest path is the only thing worth returning: it is the evidence, and the
    // pass condition. A green run that produced no manifest proved nothing.
    return {
      relayed: answer,
      passCondition:
        'a MANIFEST: line above, whose manifest reports answered === the number of source lines and errored === 0',
    }
  },
})
